name: PHP is the best language in the world
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

# i18n
gems: ['jekyll-paginate', 'jekyll-multiple-languages-plugin']
languages: ['en', 'cn']
exclude_from_localizations: ["js", "images", "css"]
